= NOST
David Thaller
:sectnums:
:toc:

== Kaufhaus


[plantuml, kaufhaus]
----
@startuml

class Kaufhaus{
    kaufhausId: Id
}

class Produkt{
    {static}produktID: int
    angebot: int
}

class Rechnung{
    datum: DateTime
    kassaNr: int
}

class Kauf{
    {static}kaufNr: int
    kassaNr: int
    datum: DateTime
}

Kaufhaus "*" -- "*"Produkt

Produkt "*" -- "*" Rechnung

(Produkt, Rechnung) ... Kauf


@enduml
----

== Fragen
. Welche Branches benötigen Sie? Erklären Sie kurz warum?
* Man benötigt Branches für jede Klasse und Änderungen.
Zum Beispiel wird ein Branch namens "feature/werk" benötigt, um die Klasse "Werk" zu implementieren.
Im Allgemeinen braucht man Branches für das Implementieren von neuen Features. deshalb werdenBranches "feature/featureName" genannt. +
`git checkout main +
git merge feature/werk +
git push`

. Wann müssen sie einen Stash erstellen?
* Ich muss ein Stash erstellen, wenn ich einen Merge Konflikt gerate. +
Durch git stash verstecke ich meine Änderungen und hole mir die Änderungen von dem remote Repository. Somit kann man sich anderen Aufgaben witmen und die Änderungen später aufspielen.


. Welchen Zweck erfüllt eine Staging Area?
* Staging Area = Vorbereitungsraum
* Auf die Staging Area bereitet man die Files von der Working Copy zum committen vor -> `git add .` -> `git commit -m "message"`
* Es kann bestimmt weerden, welche Files auf das remote repo comitted werden soll