@startuml

class Kaufhaus{
    kaufhausId: Id
}

class Produkt{
    {static}produktID: int
    angebot: int
}

class Rechnung{
    date: DateTime
    kassaNr: int
}



Kaufhaus "*" -- "*"Produkt

Produkt "*" -- "*" Rechnung

(Produkt, Rechnung) ... Buchung


@enduml